### ISSUE TITLE
Help for non-command topics

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#11]
As my application is evolving, I'm finding that providing documentation for "topics" rather than "commands" is becoming more necessary.  For example, a number of commands use a common syntax for describing "filters", but including a discussion of how "filters" work into each command's help is redundant (and causes documentation rot).  I'd rather not force the user to go outside of the program and view the manual page.

I don't have a clean suggestion for how to accomplish this given the current help implementation.  One really hacky option would be to create "invisible" commands that exist solely for their documentation.

**Comment by sbakker** [comment]
Mmmh, that's a tricky one. A fully, self-documented application was not in my original scope, I must confess.

Still, you could work on a command that just spawns an `info`, `man` or `perldoc` command...

```
$cli->add_command( Term::CLI::Command->new(
    name => 'info',
    summary => 'show documentation on various topics',
    description => "Show extended documentation for broad topics",
    arguments => [ Term::CLI::Argument::String->new(name => 'topic') ],                                                                                                                                                                                                                                                       
    callback => sub {
        my ($self, %args) = @_;
        return %args if $args{status} < 0;
        my $topic = $args{arguments}->[0];
        system('perldoc', $topic);
        $args{status} = $?;
        return %args;
    }
);
```

In this example, you could also create additional POD files in your library directory, under `MyApp::Doc` for example, and stick the `MyApp::Doc::` prefix on the `$topic` argument before calling `perldoc`.
