### ISSUE TITLE
RFE: Loading Commands on demand

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#15]
For development sanity, I've split my commands into a hierarchy of modules, e.g.:

├── Config
│   ├── Load.pm
│   ├── Reset.pm
│   ├── Save.pm
│   ├── Set.pm
│   └── Show.pm
├── Filters
│   ├── Add.pm
│   ├── Collection
│   │   ├── Add.pm
│   │   ├── Copy.pm
│   │   ├── Delete.pm
│   │   ├── Edit.pm
│   │   └── List.pm
│   ├── Collection.pm
│   ├── Copy.pm
│   ├── Delete.pm
│   ├── Edit.pm
│   ├── List.pm
│   ├── Load.pm
│   ├── Reset.pm
│   ├── Resolve.pm
│   └── Save.pm
└── Filters.pm

Each of the top level modules essentially intializes the `Term::CLI::Command::commands` attribute via this call:

`        commands => load_commands( __PACKAGE__ ),`

where `load_commands` uses `Module::Loader` to search the `__PACKAGE__` namespace and load the modules, after which it instantiates the sub-commands, and returns them.

This makes it easy to add commands, and may one day allow users to add their own.  However, it comes with a cost; lots of disk access at startup time loading commands that may never be used.  On a machine reading from local disk, that's not a problem, but $work uses network mounts which can have quite a bit of latency, so startup time can be sloooow.

One solution is of course to flatten my hierarchy by moving code into top level modules, but I think a better option to investigate is to load commands on demand, distributing the load time.  I see three triggers for a load: help, completion, and command lookup. Help requires fully loading all of the commands; completion and command lookup require one level of lookup.

I haven't explored this much, beyond the idea that the `commands` attribute would allow coderefs as well as objects.  Any thoughts?

**Comment by sbakker** [comment]
This is kind of "lazy evaluation" that you're after, right? It's an interesting idea. It might be possible to do something with CodeRefs, similar to what we've done for Enum arguments. I'll put on my thinking cap.

**Comment by sbakker** [comment]
I think the latest enhancements allow you to do this via a CodeRef argument to `commands`; combined with `add_command` and `delete_command` this should give you plenty of room to swing that particular cat. ;-)

Let me know if it makes sense.

**Comment by djerius** [comment]
Thanks; been out of the loop for a bit, will poke at this.  No cat swinging though. Did have a cat who loved being used as a curling stone.
