### ISSUE TITLE
state passed to validate() is not current for single argument with multiple values

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#21]
I'm prototyping context-sensitive completion and validation for traversing a nested data set.  Because the dataset may be of arbitrary depth, I need to use a single argument with multiple values which uses context to complete and validate the next key.

```
use v5.10.0;
use strict;
use warnings;

package Argument {

    use Term::CLI::Argument;
    use Term::CLI::Util qw( find_text_matches );

    use Moo;
    extends 'Term::CLI::Argument';

    has cache => (
        is      => 'ro',
        default => sub {
            {
                a => {
                    b => {},
                    c => {
                        d => {},
                        e => {},
                    },
                },
            }
        } );

    sub _processed {
        my ( $state ) = @_;
        my @processed = @{ $state->{processed} // [] };
        shift @processed;
        \@processed;
    }

    sub validate {
        my ( $self, $subtopic, $state ) = @_;

        say STDERR "\nvalidate: subtopic: ${ \($subtopic || '<none>')}: previous args: ",
          join( ', ', @{ $state->{processed} // [] } );

        my $topic  = $self->cache;
        my $parent = _processed( $state );
        $topic = $topic->{$_} for @$parent;

        return exists $topic->{$subtopic}
          ? $subtopic
          : $self->set_error( "no further subtopics for ${ \join( '.', @$parent )}" );
    }

    sub complete {
        my ( $self, $subtopic, $state ) = @_;

        say STDERR "\ncomplete: subtopic: ${ \($subtopic || '<none>')}: previous args: ",
          join( ', ', @{ $state->{processed} // [] } );

        my $topic  = $self->cache;
        my $parent = _processed( $state );
        $topic = $topic->{$_} for @$parent;

        my @subtopics = sort keys %$topic;
        return @subtopics if !length $subtopic;
        return find_text_matches( $subtopic, \@subtopics );
        return $self->set_error( "no further subtopics for ${ \join( '.', @$parent )}" );
    }
}

use Term::CLI;

my $cli = Term::CLI->new(
    commands => [
        Term::CLI::Command->new(
            name      => 'info',
            arguments => [
                Argument->new(
                    name      => 'arg',
                    min_occur => 0,
                    max_occur => 0,
                )
            ],
        ),
    ],
);


while ( my $input = $cli->readline ) {
    $cli->execute_line( $input );
}

```
Argument completion works fine; validation does not, as the state is not set up correctly during validation.  Here's an example interaction:

```
~> info <TAB>
complete: subtopic: <none>: previous args: info
a <TAB>
complete: subtopic: <none>: previous args: info, a
b<TAB>
complete: subtopic: b: previous args: info, a
<ENTER>

validate: subtopic: a: previous args: 

validate: subtopic: b: previous args: 
ERROR: arg#2 (arg), 'b': no further subtopics for  
```
Note the lack of state about previous arguments passed to validate.

**Comment by sbakker** [comment]
Hi, seem to have hit on the snag that I feared: the `$state` that is passed to `validate` is not the same as the one that is passed to `complete`... Compare the documentation on `Term::CLI::Element` (`complete`) and `Term::CLI::Argument` (`validate`). The state that is passed to `validate` is the same as that passed to the callback function (`Term::CLI::Role::CommandSet`).

The state in case of `validate` does not contain a `processed` or `unprocessed` key, but rather a `arguments` and `unparsed` key; these have slightly different semantics: `processed`/`unprocessed` contain "words", including commands/sub-commands. In the case of `validate`, the `arguments` contains only arguments.

So, your `validate` could be fixed as:

```
    sub validate {
        my ( $self, $subtopic, $state ) = @_;
          
        say STDERR "\nvalidate: subtopic: ${ \($subtopic || '<none>')}: previous args: ",
          join( ', ', @{ $state->{arguments} // [] } );
          
        my $topic  = $self->cache;
        my $parent = $state->{arguments};
        $topic = $topic->{$_} for @$parent;
          
        return exists $topic->{$subtopic}
          ? $subtopic
          : $self->set_error( "no further subtopics for ${ \join( '.', @$parent )}" );
    }     
```

This works for commands with arguments, but I'm not sure what happens in the face of "command sub-command argument" (I suspect `validate` will work, `complete` will fail), and "command argument sub-command argument" (I suspect both will fail). The only way to keep that sort of context information would be to pass a parse tree.

**Comment by sbakker** [comment]
Yep, try doing this:

```
my $cli = Term::CLI->new(
    commands => [
        Term::CLI::Command->new(
            name      => 'show',
            commands  => [
                Term::CLI::Command->new(
                    name      => 'info',
                    arguments => [
                        Argument->new(
                            name      => 'arg',
                            min_occur => 0,
                            max_occur => 0,
                        )
                    ],
                ),
            ],
        ),
        Term::CLI::Command::Help->new,
    ],
);
```
Completion will now be broken, validation will not. The reason is that for `complete` the first two words should now be skipped. Now, if we had a state that included a parse tree and a current_node, this would be salvageable, but boy, it gets complicated quickly.

**Comment by sbakker** [comment]
A parse tree would typically look like:

```
   Current node ----+   
                    |   
                    V   
show    info    a   c   e

$parse_tree = {                         # <---+   
    object => $show_cmd,                #     |   
    value  => 'show',                   #     |   
    prev   => undef,                    #     |   
    next   => {                         # <-----+ 
        object => $info_cmd,            #     | | 
        value  => 'info',               #     | | 
        prev   => $show_cmd,            # ----+ | 
        next   => {                     # <-------+
            object => $arg_obj,         #       | |
            value  => 'a',              #       | |
            prev   => $info_node,       # ------+ |
            next   => {                 # <---------+
                object => $arg_obj,     #         | |
                value  => 'c',          #         | |
                prev   => $a_node,      # --------+ |
                next   => {             #           |
                    object => undef,    #           |
                    value  => 'e',      #           |
                    prev   => $c_node,  # ----------+
                    next   => undef,    #
                }
            }
        }
    }
}
```
And validate/complete functions would be given a `$parse_tree` reference along with a `$current_node` reference. That way, the functions could back track `prev` pointers to the desired beginning (such as the start of a list of `Argument` objects), and take it from there. That would be food for an "advanced" tutorial!

Alternatively, this can be presented as an array with an index (since it's basically just a doubly linked list).

**Comment by sbakker** [comment]
I think I found a solution that adds a `processed` key to the validation state as well. Both for validate and complete, the structure is changed to be an arrayref of hashrefs:

```
[ 
  { element => $cmd_obj_ref, value => 'cmd' },
  { element => $arg_obj_ref, value => 'arg' }, 
  ...
]
```

The `_processed` function then needs to be turned into a method;

```
    sub _processed {
        my ( $self, $state ) = @_;
        my $processed = $state->{processed} // [];
        my @processed;
        my $i = $#{$processed};
        while ( $i && ref $processed->[$i]->{element} eq ref $self ) {
            unshift @processed, $processed->[$i]->{value};
            $i--;
        }
        return \@processed;
    }
```
This will search back in the list of processed elements to find the start of the arguments of this particular type. This way, it works in commands, sub-commands, commands mixed with arguments and sub-commands, ...

It does mark a breaking change though. The `processed` list in `complete` will have to be accessed differently.

**Comment by sbakker** [comment]
The abovementioned changes have been pushed to `dev`.

**Comment by djerius** [comment]
> Hi, seem to have hit on the snag that I feared: the `$state` that is passed to `validate` is not the same as the one that is passed to `complete`... Compare the documentation on `Term::CLI::Element` (`complete`) and `Term::CLI::Argument` (`validate`). The state that is passed to `validate` is the same as that passed to the callback function (`Term::CLI::Role::CommandSet`).

Oh. Rats. Sorry about that.  You have taken it and run with it, which I very much appreciate.  Would a hash-based Argument like what I prototyped be of interest as a core offering, or is it more along the lines of an example extension?

**Comment by sbakker** [comment]
No need to apologise, I hated the inconsistency, but didn't want to break the existing code too much. With the new `processed` semantics, the two are more or less equivalent which makes client code more consistent.

The hash-based argument is definitely interesting. I did a little demo regarding context sensitive completion/validation in the `demo` folder, but it's clunky. Doing this in a more generic way (`Term::CLI::Argument::Tree`?) could be very nice.

**Comment by djerius** [comment]
> The hash-based argument is definitely interesting. I did a little demo regarding context sensitive completion/validation in the `demo` folder, but it's clunky. Doing this in a more generic way (`Term::CLI::Argument::Tree`?) could be very nice.

Another option, which I've used for presenting hierarchical configuration options, is to flatten the hash (e.g. via Hash::Fold) and use Argument::Enum to present the user with the entire hierarchy at once. The initial auto-complete is a bit daunting, but as its not always obvious where a configuration option is located, presenting the entire hierarchy is more likely less frustrating to a user than forcing them to try every branch. There's obviously a limit to how far you can push this approach.

**Comment by djerius** [comment]
Typo at line 280 in [lib/Term/CLI/Role/CommandSet.pm](https://github.com/sbakker/perl-Term-CLI/blob/a8c6248b48ff2402e2d5dfdc8267504e5f21aeba/lib/Term/CLI/Role/CommandSet.pm#L280)?  I think the value for `processed` should be <s>a hash, not an array</s> an array of hashes.

    276     elsif ( my $cmd = $self->find_command( $words[0] ) ) {
    277         shift @words;
    278         @list = $cmd->complete(
    279             $text => {
    280                 processed   => [
    281                     element => $cmd,
    282                     value   => $cmd->name,
    283                 ],
    284                 unprocessed => \@words,
    285                 options => {},
    286             }
    287         );
    288     }

**Comment by sbakker** [comment]
Yeah, noticed that one as well... Fixed it.
