### ISSUE TITLE
RFE: output negatable options in 

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#27]
Currently the negated version of a negatable option isn't shown in the usage output, e.g. `summary!` is listed as `--summary`, not also `--no-summary`.

The fix might as simple as making `Term::CLI::option_names` return both.

**Comment by sbakker** [comment]
In the end it required a fix in `lib/Term/CLI/Command.pm` (`option_names`) for completion and `lib/Term/CLI/Role/HelpText.pm` (`get_options_summary`) for the usage text.

**Comment by sbakker** [comment]
Thanks for the RFE. Good one. ;-)

**Comment by djerius** [comment]
Thanks!  Thought I give you a few months breathing room before starting in with new RFEs.

Although, TBH, everything is working great.
