### ISSUE TITLE
SIGPIPE in t/065-Term-CLI-Command-Help.t 

### ISSUE THREAD

**Issue by eserte** [sbakker/perl-Term-CLI#5]
t/065-Term-CLI-Command-Help.t may fail without further messages. Summary suggests that a SIGPIPE (status 13) happened here:
```
Test Summary Report
-------------------
t/065-Term-CLI-Command-Help.t         (Wstat: 13 Tests: 23 Failed: 0)
  Non-zero wait status: 13
  Parse errors: Bad plan.  You planned 25 tests but ran 23.
```
Seen on ~~freebsd and~~ some linux systems, but the results are mixed, there are also passes on the same systems.

**Comment by sbakker** [comment]
Thanks. I was wondering what was causing this behaviour. It's quite likely due to the attempt to pipe data into an external pager. I've made some changes, allowing the output to be dumped to STDOUT directly. That *should* take care of it. I'll upload later today.
