### ISSUE TITLE
Tutorial's exit command doesn't save history

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#8]
Hi,
Thanks for the module and the tutorial, which is very helpful.  One thing that I noticed is that the `exit` command won't result in the command line history being saved.  It calls `execute_exit` which calls Perl's `exit` function directly, which short circuits the example code writing out the command line history, that is, the `write_history` call is never reached:
```
$cli->read_history(); 
while (defined (my $l = $cli->readline)) { ...} 
$cli->write_history()
    or warn "cannot write history: ".$cli->error."\n";
```
Some suggested approaches I came up with:

Use an `END` block, but this requires that `$cli` be global:
```
END{ $cli and $cli->write_history()
    or warn "cannot write history: ".$cli->error."\n";
}
```

Pass an extra value back via the callback's return which is used to escape the while loop, e.g.
```
callback => sub ( $self, %args ) {
            return ( %args, exit => 1 );
        },
```
Then,
```
$cli->read_history();
while ( my $input = $cli->readline() ) {
    my %args =  $cli->execute( $input ); 
    last if $args{exit};
}
$cli->write_history()
  or warn "cannot write history: " . $cli->error . "\n";
```
Use [Syntax::Keyword::Defer](https://metacpan.org/pod/Syntax::Keyword::Defer), 
```
$cli->read_history(); 
defer {
 $cli->write_history()
    or warn "cannot write history: ".$cli->error."\n";
}
while (defined (my $l = $cli->readline)) {...} 
```
The nice thing about using `defer` (compared to `END`) is that `$cli` doesn't have to be global, and it is resilient against exceptions.  And, it's now been [introduced](https://github.com/Perl/perl5/pull/19019) into a future Perl.

**Comment by sbakker** [comment]
Hi, thanks for this! Yeah, I didn't take this into account.

Mind you, it *is* possible to access the CLI object from the callback. Since you get a `$cmd` reference, which is a `Term::CLI::Command`, it has a `root_node` (via the `CommandSet` role). That `root_node` will point to the top-most `CommandSet` in the hierarchy, i.e. the `Term::CLI` object itself.

I'll add some lines regarding the various options. The `defer` is very nice.

**Comment by sbakker** [comment]
I've updated the docs and also added a `cleanup` argument to the `Term::CLI->new` method. Documented the various techniques in `Term::CLI::Tutorial`.

**Comment by djerius** [comment]
Thanks!
