### ISSUE TITLE
Make Term::CLI::Argument::Enum value list dynamic

### ISSUE THREAD

**Issue by djerius** [sbakker/perl-Term-CLI#9]
I'd like to have completion based upon a dynamic run-time selection of arguments.  I think that this can easily be accomplished by allowing the `value_list` argument to `Term::CLI::Argument::Enum` to also be a sub ref which will be called from the `complete` method.

That way I don't have to write a special Argument class to do this.

Interested?  If so I'll submit a PR.

**Comment by sbakker** [comment]
I like it, yes! Please send me a PR.
